### ISSUE TITLE
CairoSVG with plots of rasterGrobs creates images that don't display well with Firefox, Inkscape

### ISSUE THREAD

**Issue by richierocks** [s-u/Cairo#14]
I just filed a bug report about `grDevices::svg`, and the same issue (with the same fix) affects `Cairo::CairoSVG` too.

https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16594 

Related to https://github.com/s-u/Cairo/issues/8

cc: @jeffreyhorner @hadley @HenrikBengtsson

**Comment by s-u** [comment]
This has nothing to do with the Cairo package. As per discussion on R-devel this is a bug in rendering software. If you really want to add work-around for non-compliant software, you'll have to do it upstream, i.e., file a request against the cairographics library. Neither R nor the Cairo package has any control over the generated SVG content.
