### ISSUE TITLE
'family' argument of plot/main/... ignored

### ISSUE THREAD

**Issue by flying-sheep** [s-u/Cairo#17]
``` r
CairoPDF()
plot(sqrt, family = 'Fira Code')
dev.off()
```

I expect that plot to have the font I specified. The same applies for calls to `main`/`xlab`/…

**Comment by s-u** [comment]
Font family was ignored in the FreeType back-end. This has now been added both for plain FreeType and Harfbuzz rendering in 7a936f7.

**Comment by s-u** [comment]
Should be now supported in Cairo 1.6-0 with Harfbuzz back-end.
