### ISSUE TITLE
Support ligatures

### ISSUE THREAD

**Issue by flying-sheep** [s-u/Cairo#18]
``` r
CairoFonts(bold = 'Fira Code:style=Regular')
CairoPDF()
plot(sqrt, main = 'foo <- bar != baz')
dev.off()
```

I expect to see [Fira Code’s](https://github.com/tonsky/FiraCode) ligatures, but all text is separate

**Comment by s-u** [comment]
For the same reasons as in #23 this is not supported by [cairographics](https://cairographics.org). See #23 for a new branch that supports complex font shaping via Harfbuzz which also includes ligatures. I'll close this and track the rest in #23.

```r
library(Cairo)
CairoFonts(bold = 'Fira Code:style=Regular')
Cairo(dpi=100)
plot(sqrt, main = 'foo <- bar != baz')
dev.off()
```
![plot](https://user-images.githubusercontent.com/2073427/165231644-c068bca6-3ed5-46ab-8827-1547512d09aa.png)
