### ISSUE TITLE
Right to left fonts like Arabic and Persian are disjointed and reversed

### ISSUE THREAD

**Issue by m-hoseini** [s-u/Cairo#23]
Hello,

When I save a plot containing rtl font as cairo_pdf, characters are disjointed and reversed. Example:

`library(Cairo)`
`cairo_pdf("test.pdf")`
`plot(0, main="سلام علیکم")`
`dev.off()`

The PDF output looks like this. Instead of "سلام علیکم" it prints "م‌ک‌ی‌ل‌ع م‌ا‌ل‌س"
![image](https://user-images.githubusercontent.com/37844191/49104323-ea9b6680-f292-11e8-9f02-5af59964fc24.png)

**Comment by s-u** [comment]
The internal rendering in the [cairographics](https://www.cairographics.org) library does not support anything other than LTR text, unfortunately. 

I have now started as experimental branch which uses [Harfbuzz](https://harfbuzz.github.io) and [ICU](https://icu.unicode.org) to split text by language/script and renders them separately as glyphs: https://github.com/s-u/Cairo/tree/feature/harfbuzz

This seems to work:
```r
Cairo::Cairo(dpi=100)
Cairo::CairoFonts("Tahoma")
plot(1, 1, xlab="سلام علیکم", ylab="ABC אבג DEF",ty="n")
text(1, 1 ,"قرأ Wikipedia™‎ طوال اليوم.",cex=2)
dev.off()
```
![plot](https://user-images.githubusercontent.com/2073427/165229324-fa6ed6ec-d2ad-4f3b-9217-1d6d9277aace.png)

Please note that `cairo_pdf` is NOT from the Cairo package but rather the built-in R functions. You have to use one of the `Cairo` functions instead (e.g. `CairoPDF` for PDF). Finally, the fonts used must support all the glyphs rendered and only few fonts do so some trial and error may be necessary.

Also note that this will only work if the system has all libraries necessary, you should see at installation time:

```
checking whether Harfbuzz layout is desired... auto
checking whether Harfbuzz + ICU works... yes
```

If it shows `no` then something is not available and you'd have to check `config.log` for details.

**Comment by s-u** [comment]
Should be now supported in Cairo 1.6-0 with Harfbuzz back-end.
