### ISSUE TITLE
configure: error: Cannot use cairo-ft backend, although cairo claims it is working.

### ISSUE THREAD

**Issue by CSBioAzim** [s-u/Cairo#28]
Hi, 

I'm trying to install Cairo on my MacBook using R version 4.0.3 (2020-10-10). 
I tried to install it from bioconductor, Github repo, and binary file. I got the same error in all the cases. 
Here is the error:

Here is the error I get
```
configure: error: Cannot use cairo-ft backend, although cairo claims it is working.
LAGS/CAIRO_LIBS accordingly.
ERROR: configuration failed for package ‘Cairo’
* removing ‘/usr/local/lib/R/4.0/site-library/Cairo’
* restoring previous ‘/usr/local/lib/R/4.0/site-library/Cairo’
```

Can you please fix this error for the recent version of the R?

**Comment by s-u** [comment]
This is problem with your `libcairo` setup - please check `config.log` to see what is failing exactly. macOS does not provide `libcairo` and you are not using CRAN R binary (which works) so you're on your own and thus you have to provide 1) `config.log` 2) exact details how you installed `libcairo` 3) exact details how you tried to install Cairo (including full output)
