### ISSUE TITLE
Looking for libraries in odd places

### ISSUE THREAD

**Issue by daviddehoog** [s-u/Cairo#29]
Had a few issues loading the Cairo package on MacOSX (Big Sur) with "R version 4.0.5 (2021-03-31)". I installed a number of missing libraries for X11/Quartz with Homebrew and they were placed under /usr/local/lib/.

I had to add links for six libraries: 
libICE.6.dylib		libX11.6.dylib		libXrender.1.dylib
libSM.6.dylib		libXext.6.dylib		libXt.6.dylib

When I attempted to load the Cairo package, it couldn't find these libraries and instead was looking for them in /opt/11/lib/. I added symbolic links to keep Cairo and the libraries talking.

Here's an example output from trying to load Cairo:
> library(Cairo)
Error: package or namespace load failed for ‘Cairo’:
 .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found

**Comment by s-u** [comment]
@daviddehoog You shouldn't mix homebrew and CRAN binaries. Either compile everything from source with Homebrew or use the official releases, not both. 

The CRAN release works out of the box, just read the download page - you need to install XQuartz (https://www.xquartz.org/), thats' all.
