### ISSUE TITLE
How can I make the "tiff format" become "TURE" on my PC?

### ISSUE THREAD

**Issue by Skywings96** [s-u/Cairo#31]
I want to use Cairo to export pictures in tiff format, but after I ran "Cairo.capabilities()",  then I found that the tiff format is FALSE. How can I solve this problem?

**Comment by s-u** [comment]
You need to make sure you compile Cairo with tiff support. If you want more details, you'd have to provide more details about R and your OS (at the very least `sessionInfo()`) and how exactly you installed Cairo.

**Comment by s-u** [comment]
Closing due to lack of follow up
