### ISSUE TITLE
library(Cairo) gives error

### ISSUE THREAD

**Issue by dcaud** [s-u/Cairo#34]
`library(Cairo)` results in:

> Error: package or namespace load failed for ‘Cairo’:
>  .onLoad failed in loadNamespace() for 'Cairo', details:
>   call: dyn.load(file, DLLpath = DLLpath, ...)
>   error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Cairo/libs/Cairo.so':
>   dlopen(/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Cairo/libs/Cairo.so, 0x0006): Library not loaded: /opt/X11/lib/libXrender.1.dylib
>   Referenced from: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Cairo/libs/Cairo.so
>   Reason: tried: '/opt/X11/lib/libXrender.1.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/libXrender.1.dylib' (no such file)

Any ideas how to solve this?

`sessionInfo()`

> R version 4.1.2 (2021-11-01)
> Platform: aarch64-apple-darwin20 (64-bit)
> Running under: macOS Monterey 12.2.1
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] tools     stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] googleAuthR_2.0.0  firebase_1.0.1     RPostgres_1.4.3    pool_0.1.6        
>  [5] dplyr_1.0.8        shinyjs_2.1.0      shinybusy_0.3.0    shinyWidgets_0.6.4
>  [9] magick_2.7.3       colourpicker_1.1.1 shiny_1.7.1       
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.8.3      pillar_1.7.0      compiler_4.1.2    bslib_0.3.1      
>  [5] later_1.3.0       jquerylib_0.1.4   base64enc_0.1-3   digest_0.6.29    
>  [9] bit_4.0.4         gargle_1.2.0      memoise_2.0.1     tibble_3.1.6     
> [13] jsonlite_1.8.0    lifecycle_1.0.1   pkgconfig_2.0.3   rlang_1.0.2      
> [17] DBI_1.1.2         cli_3.2.0         fastmap_1.1.0     httr_1.4.2       
> [21] fs_1.5.2          generics_0.1.2    vctrs_0.4.0       htmlwidgets_1.5.4
> [25] sass_0.4.1        askpass_1.1       hms_1.1.1         tidyselect_1.1.2 
> [29] bit64_4.0.5       glue_1.6.2        qpdf_1.1          R6_2.5.1         
> [33] fansi_1.0.3       purrr_0.3.4       blob_1.2.3        magrittr_2.0.3   
> [37] promises_1.2.0.1  ellipsis_0.3.2    htmltools_0.5.2   assertthat_0.2.1 
> [41] jose_1.2.0        mime_0.12         xtable_1.8-4      httpuv_1.6.5     
> [45] utf8_1.2.2        miniUI_0.1.1.1    openssl_2.0.0     cachem_1.0.6     
> [49] crayon_1.5.1

**Comment by s-u** [comment]
You are running arm64 version of R but don't have XQuartz for arm64. Install it from https://www.xquartz.org/releases/XQuartz-2.8.1.html

**Comment by michaelbach** [comment]
Thank you! Solved my problem too.
