### ISSUE TITLE
Grossly inconsistent font size between type="pdf" and type="png"

### ISSUE THREAD

**Issue by zackw** [s-u/Cairo#44]
The attached PNG and PDF were both rendered from an identical ggplot2 plot (`dput(ggplotGrob(plot))` is also attached) using this procedure

```
save_Cairo <- function (filename, plot, type) {
    Cairo(width=10, height=4, units="cm", dpi=300, type=type, file=filename)
    print(plot)
    invisible(dev.off())
}
```

so the _only_ difference is `type="pdf"` vs `type="png"`.  The PNG rendering is correct.  In the PDF, however, every piece of text is much too large, as are all of the lines, and because the text takes up too much space, the plot is crushed into illegibility.

If there is a workaround of any sort, please advise.

[font-size-bug.png](https://github.com/s-u/Cairo/assets/325899/acad1896-6e2c-435c-9d6b-6440d6a3c098)
[font-size-bug.pdf](https://github.com/s-u/Cairo/files/13195974/argh.pdf)
[plot.grob.txt.gz](https://github.com/s-u/Cairo/files/13195979/plot.grob.txt.gz)

**Comment by s-u** [comment]
@zackw The `plot.grob.txt` file doesn't work - please use `saveRDS` if you want to save R objects. Ideally, use a simple, reproducible example code.

**Comment by s-u** [comment]
Closing as no reproducible example was provided
