### ISSUE TITLE
Bold or emphasized text aren't rendered properly

### ISSUE THREAD

**Issue by casperhart** [s-u/Cairo#47]
Hi Simon,

I'm looking at using Cairo to render some PDFs, but I've run in to this issue where bold and emphasized text aren't rendered as such. This is the case with `gridtext`, but also with `grid` when specifying bold text as an expression. The example code below works with `svg`, `pdf`, `cairo_pdf`, and `svglite` graphics devices, so I suspect the issue is with `Cairo`.

Neither `pdf` or `cairo_pdf` work as alternatives for me. I haven't gotten `pdf` to work with custom fonts, and `cairo_pdf` has kerning issues that make text look quite bad.

Any help would be appreciated, thanks!

Example:
```
library(gridtext)
library(grid)
library(Cairo)
library(svglite)

g1 <- gridtext::textbox_grob("this text should be **bold**, and this _emphasized_")
g2 <- grid::textGrob(expression(bold("This should also be bold")), y = 0.4)

CairoPDF("test_CairoPDF.pdf") 
grid.draw(g1) # not bold or emphasized
grid.draw(g2) # not bold
dev.off()

CairoSVG("test_CairoSVG.svg")
grid.draw(g1) # not bold or emphasized
grid.draw(g2) # not bold
dev.off()

cairo_pdf("test_cairo_pdf.pdf")
grid.draw(g1) # bold and emphasized
grid.draw(g2) # bold
dev.off()

pdf("test_pdf.pdf")
grid.draw(g1) # bold and emphasized
grid.draw(g2) # bold
dev.off()

svg("test_svg.svg")
grid.draw(g1) # bold and emphasized
grid.draw(g2) # bold
dev.off()

svglite("test_svglite.svg")
grid.draw(g1) # bold and emphasized
grid.draw(g2) # bold
dev.off()
```

**Comment by s-u** [comment]
Both examples work for me, but you have to make sure that your selected font supports bold/italic face - check with `CairoFonts()` -- if it shows the same filename for regular and bold then your system doesn't have a bold version of the font, so you may want to switch to a font that does (see the example in the help page for `CairoFonts`).

**Comment by casperhart** [comment]
Thanks for the quick response. `CairoFonts()` shows nothing, and after running the example in `?CairoFonts`... Still no output, and no bold text in the two examples:

```
> library(Cairo)
> CairoFonts() # no output
> CairoFonts(
             regular="Helvetica:style=Regular",
             bold="Helvetica:style=Bold",
             italic="Helvetica:style=Italic",
             bolditalic="Helvetica:style=Bold Italic,BoldItalic",
             symbol="Symbol", usePUA=TRUE
     )
> CairoFonts() # no output
> 
```

For context, I'm using an M-series mac, and I have R installed through miniconda. I installed Cairo through conda (`conda install r-cairo`) because installing from source was giving the error:

```
checking for pkg-config... no
configure: CAIRO_LIBS is unset, attempting to guess it.
configure: CAIRO_CFLAGS=
checking if R was compiled with the RConn patch... no
checking for cairo.h... no
configure: error: Cannot find cairo.h! Please install cairo (http://www.cairographics.org/) and/or set CAIRO_CFLAGS/LIBS correspondingly.
ERROR: configuration failed for package ‘Cairo’
```

I have tried this to no avail:

```
export CAIRO_LIBS=/opt/homebrew/opt/cairo/lib 
export CAIRO_CFLAGS=/opt/homebrew/opt/cairo/include
R --slave -e "install.packages('Cairo')"
```

I can confirm `cairo.h` is at `/opt/homebrew/opt/cairo/include/cairo/cairo.h`

Do you think it could be the installation, or would it be something else? Thank you for your patience!

**Comment by s-u** [comment]
Sorry, I think you missed what I said - if you are on macOS then "Helvetica" doesn't have bold/italic varieties, e.g.

```
>  CairoFontMatch("Helvetica")
1. family: "Helvetica", style: "Regular", file: "/System/Library/Fonts/Helvetica.ttc"
> CairoFontMatch("Helvetica:style=Bold")
1. family: "Helvetica", style: "Bold", file: "/System/Library/Fonts/Helvetica.ttc"
```

both are the same font.

You have to use a font that does -- like the example in `CairoFonts` (as I mentioned):

```
     CairoFonts(
             regular="FreeSans:style=Medium",
             bold="FreeSans:style=Bold",
             italic="FreeSans:style=Oblique",
             bolditalic="FreeSans:style=BoldOblique"
     )
```

which does have the corresponding varieties:

```
> CairoFontMatch("FreeSans:style=Medium")
1. family: "Bitstream Vera Sans", style: "Roman", file: "/usr/X11/share/fonts/TTF/Vera.ttf"
> CairoFontMatch("FreeSans:style=Bold")
1. family: "Bitstream Vera Sans", style: "Bold", file: "/usr/X11/share/fonts/TTF/VeraBd.ttf"
```

(note that difference in font files for each style)

**Comment by casperhart** [comment]
Now I see. I tried this out with Open Sans and it works like a charm. Thanks for your help!

**Comment by s-u** [comment]
Still, thanks for raising the issue - I suspect that it may make sense to check if the fonts are the same and issue a warning...

BTW: My fault about the `CairoFonts()` output - I was running the debug version of `Cairo` which shows all the loaded fonts - I didn't realize that the release was silent. I think I'll change it so that `CairoFonts()` will return the font information instead of `NULL`.
