### ISSUE TITLE
treatment of grid primitives inconsistent with standard devices

### ISSUE THREAD

**Issue by mplourde** [s-u/Cairo#9]
In base R, **grid** primitives have a default empty fill. So you could plot to concentric circles with:

```
library(grid)
grid.circle(r=.1)
grid.circle(r=.2)
dev.off()
```

When using a **Cairo** device, however, it appears to assume these shapes have a white fill.

```
CairoPNG()
grid.circle(r=.1)
grid.circle(r=.2)
dev.off()
```

If you supply an `NA` fill, parameter, the scene plots correctly.

```
CairoPNG()
grid.circle(r=.1, gp=gpar(fill=NA))
grid.circle(r=.2, gp=gpar(fill=NA))
dev.off()
```

**Comment by s-u** [comment]
See `grid` documentation - the `fill` parameter is explicitly documented as device-specific so your code should create a viewport to control parameters that are undefined such as `fill` when needed, e.g.:

```r
CairoPNG()
pushViewport(viewport(gp=gpar(fill=NA)))
grid.circle(r=.1)
grid.circle(r=.2)
dev.off()
```

FWIW note that you can use `CairoPNG(bg=NA)` for transparent background.
